### ISSUE TITLE
Have you ever run monodepth2?

### ISSUE THREAD

**Issue by zsh1223** [Jamesgender/Monodepth_V1_Pytorch#1]

**Comment by Jamesgender** [comment]
Yes, centainly.

**Comment by zsh1223** [comment]
![image](https://github.com/Jamesgender/Monodepth_V1_Pytorch/assets/130481211/a60ff61f-bb38-4efb-a52f-f226abef47fd)
Have you ever encountered this kind of error? How did you solve it. The command I trained is: Python train. py -- model_ Name mono_ Model -- log_ Dir results -- height 320-- width 1024-- weights_ Init pretrained
If it's convenient for you, could you please leave your email address so that we can communicate via email. This is my email: 2220320130@stu.xaut.edu.cn

**Comment by Jamesgender** [comment]
It looks like the image was not fed into the network correctly, I consulted my notes and found possible questions. The Monodepth2' split may cause a problem: image not exits. When the program accesses the frame before the first frame and the frame after the last frame, an error is reported because these frames do not exist.

When I encountered this problem, I printed all paths of the the training images, and found these frames not existed, e.g. -0000001.png/jpg. So I immediately knew where the problem is.

If you use stereo pair images for training, there should be no errors. And if you want to train the monodepth2 in mono method, you should change the default split. A easy way to do is using 39810 images (eigen_zhou splits) rather than 45200 images.

**Comment by zsh1223** [comment]
![image](https://github.com/Jamesgender/Monodepth_V1_Pytorch/assets/130481211/25c2268f-b6ab-4dad-9471-6dd575c7b5b3)
I have checked the source code of monodepth2. In the commands I trained, I did not set "-- split". This means it uses the default value of "eigen_zhou". I did not use 45200 images as my training set.

**Comment by Jamesgender** [comment]
Well, you can still print the path of training images, and check if the image is exist.

**Comment by zsh1223** [comment]
How should I check? Do you have sample code or commands?

**Comment by Jamesgender** [comment]
You can first try to train the Monodepth2 in stereo method. If there is no problem, that might be the problem I had encountered.

Pytorch use default function __getitem__ to get data from dataset, you can add 
" path = self. get_image_path(folder, frame_index +i, side)" in getitem, and print the path.
![image](https://github.com/Jamesgender/Monodepth_V1_Pytorch/assets/135774928/dd957577-5879-43cc-a5b0-451f052f6f8e)

**Comment by zsh1223** [comment]
![image](https://github.com/Jamesgender/Monodepth_V1_Pytorch/assets/130481211/7605654d-5387-4513-a214-ce66f8e373e3)
These paths actually exist

**Comment by Jamesgender** [comment]
You should let the training continue, until the error comes out. 
If all the images exists, you can try to check the data fed to the encoder.
![image](https://github.com/Jamesgender/Monodepth_V1_Pytorch/assets/135774928/6f1f1b76-d661-4d42-85f2-ea176504f00b)
Debug the code and check the input. If there is a value of type nonetype in the input, then this is where the problem lies.

**Comment by zsh1223** [comment]
![image](https://github.com/Jamesgender/Monodepth_V1_Pytorch/assets/130481211/333073a7-c9a0-482d-bc88-805e8d57b7f8)
My stereo program is running with an error message

**Comment by zsh1223** [comment]
![image](https://github.com/Jamesgender/Monodepth_V1_Pytorch/assets/130481211/2536ecdf-b983-4546-ab72-ddddf5a96e5a)
My mono program is running with an error message
